# Site
repository: germanp/germanp.github.io
# favicon: images/favicon.ico

# Personal info
name: Germán Martín Podestá
title: Full-stack Web Developer
email: german.m.podesta@gmail.com
website: https://germanp.github.io

# Social links
github_username:  germanp
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: germanmpodesta
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm an information systems graduate with 8+ years of experience in software development. I have strong skills in django and python and I have worked with server administration and CI. I also worked with vuejs in the frontend.

  I believe that well-documented code and decisions are keystone when building a good product, they favor communication saving a lot of effort from misunderstandings and frustration. They also encourage communication and teamwork.

  I am most skilled in: <mark>Python</mark> <mark>Javascript</mark> <mark>Typescript</mark> <mark>Unit Testing</mark> <mark>Docker</mark> <mark>Deployment</mark> <mark>CI</mark>

# Projects Section
projects_title: Featured Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Besides working on software engineering, which I love, I like practising Yoga
  and taking care of my pets.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
